### ISSUE TITLE
Error: Number of channels mismatch! on Denon X4800 with both subs labelled SWMIX in ADY

### ISSUE THREAD

**Issue by reedbotwright** [ObsessiveCompulsiveAudiophile/AudysseyOne#8]
Helping a user with the A-1 script and they get the error: "Error: Number of channels mismatch!" When I check their configuration in their AVR, everything looks good ("Standard" sub config for the 2 subs and both fire during sweeps), but their ADY shows both subs to be labelled SWMIX. 

Is there a change to their Denon config to address this? Or can I just change the ADY to be the typical SW1 and SW2?

**Comment by ObsessiveCompulsiveAudiophile** [comment]
SWMIX name convention is OK, some models name both subs SWMIX rather than
SW1 and SW2 but the "number of channels mismatch" makes me think both sub
measurements are being carried over to REW. This will happen when they have
both been measured separately by Audyssey. That should only happen in
"directional bass" setting. A1 will check if there's response data (and
normally second, third and fourth subs will not have any data under
responseData) in the detectedChannels and carries it over as measurement to
REW. Now, normally an AVR model naming subs SWMIX is an older model and
will not have directional bass mode but it can be done by using the app
settings. If that's the case, measurements will need to be repeated in
"standard bass" mode I am afraid. One cannot optimize "directional bass"
mode.

In general, every speaker needs to have the same number of
measurements (equal to the total mic positions) imported to REW plus one
set of measurements for one sub. When that's not the case, that error will
be thrown.

Let me know if you need further help.

OCA

**Comment by reedbotwright** [comment]
Helping another chap who has the same issue, this time with only one sub and using the Marantz AV10. Also swears he doesn't have directional bass enabled, not that it should even be an option with only one sub. 
[pre-A1-baseline.zip](https://github.com/ObsessiveCompulsiveAudiophile/AudysseyOne/files/14847218/pre-A1-baseline.zip)

**Comment by ObsessiveCompulsiveAudiophile** [comment]
One is asking for a center speaker distance input with this ady at the
beginning and once a distance value is input it runs smoothly. I used 3 and
the result is attached.

When A1 asks for center speaker distance input, it's because Audyssey
during the measurements found out SW distance will need to be over the 6m
limit (wrongly most of the time). Then Audyssey then will delete all
speaker distances in the ady file (you can check that in the original ady
file, they are all 0) and it will assign the maximum possible distance to
the sub (in this case it was set to 8.52m). When you check the distances in
the app post calibration, the app will show you speaker distances by
calculating them while keeping the sub at max. But these distances are not
in the ady file, it's the app hiding the fact from the user that it cannot
align the sub to speakers.

What you enter as value doesn't need to be precise, One calculates relative
time delays. A ballpark figure would be fine so long as it's not too short
and some speakers will end up with negative distances.

https://drive.google.com/file/d/1eXYS_Mo9PCp4OTdsDP7iji1kK_MYUDZy/view?usp=sharing

**Comment by ObsessiveCompulsiveAudiophile** [comment]
Audyssey One v1.3 coming shortly...No biggy, minor updates.

**Comment by reedbotwright** [comment]
I believe this was an issue with the user not setting the REW max measurements to 300 and hitting the limit. Consider it closed.

**Comment by ObsessiveCompulsiveAudiophile** [comment]
"Audyssey One" minor compatibility update today (v1.3x) * Updated to
address ongoing REW Beta API changes. Please use the provided REW Beta 21
link within A1 until the next update ensures compatibility with the latest
REW beta versions. * Revised default Dr. Toole target curve for roll-off
filters in your receiver, providing full flat response throughout the
audible frequency range. * Optimized subwoofer volume level calculation
algorithm for increased compatibility.
